// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springroo.salary.domain;

import com.springroo.salary.domain.AdvancedPayments;
import com.springroo.salary.domain.AdvancedPaymentsDataOnDemand;
import com.springroo.salary.domain.AdvancedPaymentsIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AdvancedPaymentsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AdvancedPaymentsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AdvancedPaymentsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AdvancedPaymentsIntegrationTest: @Transactional;
    
    @Autowired
    private AdvancedPaymentsDataOnDemand AdvancedPaymentsIntegrationTest.dod;
    
    @Test
    public void AdvancedPaymentsIntegrationTest.testCountAdvancedPaymentses() {
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to initialize correctly", dod.getRandomAdvancedPayments());
        long count = AdvancedPayments.countAdvancedPaymentses();
        Assert.assertTrue("Counter for 'AdvancedPayments' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AdvancedPaymentsIntegrationTest.testFindAdvancedPayments() {
        AdvancedPayments obj = dod.getRandomAdvancedPayments();
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to provide an identifier", id);
        obj = AdvancedPayments.findAdvancedPayments(id);
        Assert.assertNotNull("Find method for 'AdvancedPayments' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AdvancedPayments' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AdvancedPaymentsIntegrationTest.testFindAllAdvancedPaymentses() {
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to initialize correctly", dod.getRandomAdvancedPayments());
        long count = AdvancedPayments.countAdvancedPaymentses();
        Assert.assertTrue("Too expensive to perform a find all test for 'AdvancedPayments', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AdvancedPayments> result = AdvancedPayments.findAllAdvancedPaymentses();
        Assert.assertNotNull("Find all method for 'AdvancedPayments' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AdvancedPayments' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AdvancedPaymentsIntegrationTest.testFindAdvancedPaymentsEntries() {
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to initialize correctly", dod.getRandomAdvancedPayments());
        long count = AdvancedPayments.countAdvancedPaymentses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AdvancedPayments> result = AdvancedPayments.findAdvancedPaymentsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AdvancedPayments' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AdvancedPayments' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AdvancedPaymentsIntegrationTest.testFlush() {
        AdvancedPayments obj = dod.getRandomAdvancedPayments();
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to provide an identifier", id);
        obj = AdvancedPayments.findAdvancedPayments(id);
        Assert.assertNotNull("Find method for 'AdvancedPayments' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAdvancedPayments(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AdvancedPayments' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdvancedPaymentsIntegrationTest.testMergeUpdate() {
        AdvancedPayments obj = dod.getRandomAdvancedPayments();
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to provide an identifier", id);
        obj = AdvancedPayments.findAdvancedPayments(id);
        boolean modified =  dod.modifyAdvancedPayments(obj);
        Integer currentVersion = obj.getVersion();
        AdvancedPayments merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AdvancedPayments' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdvancedPaymentsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to initialize correctly", dod.getRandomAdvancedPayments());
        AdvancedPayments obj = dod.getNewTransientAdvancedPayments(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AdvancedPayments' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AdvancedPayments' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AdvancedPaymentsIntegrationTest.testRemove() {
        AdvancedPayments obj = dod.getRandomAdvancedPayments();
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AdvancedPayments' failed to provide an identifier", id);
        obj = AdvancedPayments.findAdvancedPayments(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AdvancedPayments' with identifier '" + id + "'", AdvancedPayments.findAdvancedPayments(id));
    }
    
}
