// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springroo.salary.domain;

import com.springroo.salary.domain.AdvancedPaymentsDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AdvancedPaymentsDataOnDemand_Roo_Configurable {
    
    declare @type: AdvancedPaymentsDataOnDemand: @Configurable;
    
}
