// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springroo.salary.domain;

import com.springroo.salary.domain.Configuration;
import com.springroo.salary.domain.ConfigurationDataOnDemand;
import com.springroo.salary.domain.ConfigurationIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConfigurationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConfigurationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConfigurationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConfigurationIntegrationTest: @Transactional;
    
    @Autowired
    private ConfigurationDataOnDemand ConfigurationIntegrationTest.dod;
    
    @Test
    public void ConfigurationIntegrationTest.testCountConfigurations() {
        Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", dod.getRandomConfiguration());
        long count = Configuration.countConfigurations();
        Assert.assertTrue("Counter for 'Configuration' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConfigurationIntegrationTest.testFindConfiguration() {
        Configuration obj = dod.getRandomConfiguration();
        Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Configuration' failed to provide an identifier", id);
        obj = Configuration.findConfiguration(id);
        Assert.assertNotNull("Find method for 'Configuration' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Configuration' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConfigurationIntegrationTest.testFindAllConfigurations() {
        Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", dod.getRandomConfiguration());
        long count = Configuration.countConfigurations();
        Assert.assertTrue("Too expensive to perform a find all test for 'Configuration', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Configuration> result = Configuration.findAllConfigurations();
        Assert.assertNotNull("Find all method for 'Configuration' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Configuration' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConfigurationIntegrationTest.testFindConfigurationEntries() {
        Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", dod.getRandomConfiguration());
        long count = Configuration.countConfigurations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Configuration> result = Configuration.findConfigurationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Configuration' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Configuration' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConfigurationIntegrationTest.testFlush() {
        Configuration obj = dod.getRandomConfiguration();
        Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Configuration' failed to provide an identifier", id);
        obj = Configuration.findConfiguration(id);
        Assert.assertNotNull("Find method for 'Configuration' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConfiguration(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Configuration' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConfigurationIntegrationTest.testMergeUpdate() {
        Configuration obj = dod.getRandomConfiguration();
        Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Configuration' failed to provide an identifier", id);
        obj = Configuration.findConfiguration(id);
        boolean modified =  dod.modifyConfiguration(obj);
        Integer currentVersion = obj.getVersion();
        Configuration merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Configuration' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConfigurationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", dod.getRandomConfiguration());
        Configuration obj = dod.getNewTransientConfiguration(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Configuration' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Configuration' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Configuration' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConfigurationIntegrationTest.testRemove() {
        Configuration obj = dod.getRandomConfiguration();
        Assert.assertNotNull("Data on demand for 'Configuration' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Configuration' failed to provide an identifier", id);
        obj = Configuration.findConfiguration(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Configuration' with identifier '" + id + "'", Configuration.findConfiguration(id));
    }
    
}
