// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springroo.salary.domain;

import com.springroo.salary.domain.ProblemReports;
import com.springroo.salary.domain.ProblemReportsDataOnDemand;
import com.springroo.salary.domain.ProblemReportsIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProblemReportsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProblemReportsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProblemReportsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProblemReportsIntegrationTest: @Transactional;
    
    @Autowired
    private ProblemReportsDataOnDemand ProblemReportsIntegrationTest.dod;
    
    @Test
    public void ProblemReportsIntegrationTest.testCountProblemReportses() {
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to initialize correctly", dod.getRandomProblemReports());
        long count = ProblemReports.countProblemReportses();
        Assert.assertTrue("Counter for 'ProblemReports' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProblemReportsIntegrationTest.testFindProblemReports() {
        ProblemReports obj = dod.getRandomProblemReports();
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to provide an identifier", id);
        obj = ProblemReports.findProblemReports(id);
        Assert.assertNotNull("Find method for 'ProblemReports' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProblemReports' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProblemReportsIntegrationTest.testFindAllProblemReportses() {
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to initialize correctly", dod.getRandomProblemReports());
        long count = ProblemReports.countProblemReportses();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProblemReports', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProblemReports> result = ProblemReports.findAllProblemReportses();
        Assert.assertNotNull("Find all method for 'ProblemReports' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProblemReports' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProblemReportsIntegrationTest.testFindProblemReportsEntries() {
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to initialize correctly", dod.getRandomProblemReports());
        long count = ProblemReports.countProblemReportses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProblemReports> result = ProblemReports.findProblemReportsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProblemReports' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProblemReports' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProblemReportsIntegrationTest.testFlush() {
        ProblemReports obj = dod.getRandomProblemReports();
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to provide an identifier", id);
        obj = ProblemReports.findProblemReports(id);
        Assert.assertNotNull("Find method for 'ProblemReports' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProblemReports(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProblemReports' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProblemReportsIntegrationTest.testMergeUpdate() {
        ProblemReports obj = dod.getRandomProblemReports();
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to provide an identifier", id);
        obj = ProblemReports.findProblemReports(id);
        boolean modified =  dod.modifyProblemReports(obj);
        Integer currentVersion = obj.getVersion();
        ProblemReports merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProblemReports' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProblemReportsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to initialize correctly", dod.getRandomProblemReports());
        ProblemReports obj = dod.getNewTransientProblemReports(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProblemReports' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ProblemReports' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProblemReportsIntegrationTest.testRemove() {
        ProblemReports obj = dod.getRandomProblemReports();
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProblemReports' failed to provide an identifier", id);
        obj = ProblemReports.findProblemReports(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProblemReports' with identifier '" + id + "'", ProblemReports.findProblemReports(id));
    }
    
}
