// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springroo.salary.domain;

import com.springroo.salary.domain.StartSalarys;
import com.springroo.salary.domain.StartSalarysDataOnDemand;
import com.springroo.salary.domain.StartSalarysIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StartSalarysIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StartSalarysIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StartSalarysIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StartSalarysIntegrationTest: @Transactional;
    
    @Autowired
    private StartSalarysDataOnDemand StartSalarysIntegrationTest.dod;
    
    @Test
    public void StartSalarysIntegrationTest.testCountStartSalaryses() {
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to initialize correctly", dod.getRandomStartSalarys());
        long count = StartSalarys.countStartSalaryses();
        Assert.assertTrue("Counter for 'StartSalarys' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StartSalarysIntegrationTest.testFindStartSalarys() {
        StartSalarys obj = dod.getRandomStartSalarys();
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to provide an identifier", id);
        obj = StartSalarys.findStartSalarys(id);
        Assert.assertNotNull("Find method for 'StartSalarys' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StartSalarys' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StartSalarysIntegrationTest.testFindAllStartSalaryses() {
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to initialize correctly", dod.getRandomStartSalarys());
        long count = StartSalarys.countStartSalaryses();
        Assert.assertTrue("Too expensive to perform a find all test for 'StartSalarys', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StartSalarys> result = StartSalarys.findAllStartSalaryses();
        Assert.assertNotNull("Find all method for 'StartSalarys' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StartSalarys' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StartSalarysIntegrationTest.testFindStartSalarysEntries() {
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to initialize correctly", dod.getRandomStartSalarys());
        long count = StartSalarys.countStartSalaryses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StartSalarys> result = StartSalarys.findStartSalarysEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StartSalarys' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StartSalarys' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StartSalarysIntegrationTest.testFlush() {
        StartSalarys obj = dod.getRandomStartSalarys();
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to provide an identifier", id);
        obj = StartSalarys.findStartSalarys(id);
        Assert.assertNotNull("Find method for 'StartSalarys' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStartSalarys(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'StartSalarys' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StartSalarysIntegrationTest.testMergeUpdate() {
        StartSalarys obj = dod.getRandomStartSalarys();
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to provide an identifier", id);
        obj = StartSalarys.findStartSalarys(id);
        boolean modified =  dod.modifyStartSalarys(obj);
        Integer currentVersion = obj.getVersion();
        StartSalarys merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'StartSalarys' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StartSalarysIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to initialize correctly", dod.getRandomStartSalarys());
        StartSalarys obj = dod.getNewTransientStartSalarys(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StartSalarys' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'StartSalarys' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StartSalarysIntegrationTest.testRemove() {
        StartSalarys obj = dod.getRandomStartSalarys();
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StartSalarys' failed to provide an identifier", id);
        obj = StartSalarys.findStartSalarys(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StartSalarys' with identifier '" + id + "'", StartSalarys.findStartSalarys(id));
    }
    
}
